session_limit_max: 1
session_limit_behaviour: 0
session_limit_logged_out_message: 'You have been automatically logged out. Someone else has logged in with your username and password and the maximum number of @number simultaneous sessions was exceeded. This may indicate that your account has been compromised or that account sharing is not all owed on this site. Please contact the site administrator if you suspect your account has been compromised.'
session_limit_logged_out_message_severity: 'error'
session_limit_roles: []
